const list = [
  {
    id: 1,
    EIIN: "103149",
    schoolName: "GOLKHAR RANI KHAR HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "AKHAURA",
  },
  {
    id: 2,
    EIIN: "103150",
    schoolName: "NURPUR RUTI ABDUL HAQUE BHUIYA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "AKHAURA",
  },
  {
    id: 3,
    EIIN: "103151",
    schoolName: "BANGLADESH RAILWAY GOVT. HIGH SCHOOL, AKHAURA",
    zilla: "BRAHMANBARIA",
    upazila: "AKHAURA",
  },
  {
    id: 4,
    EIIN: "103152",
    schoolName: "AKHAURA NASRIN NABI PILOT GIRLS' HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "AKHAURA",
  },
  {
    id: 5,
    EIIN: "103153",
    schoolName: "SHAHPIR KALLA SHAHID HIGH SCHOOL, AKHAURA",
    zilla: "BRAHMANBARIA",
    upazila: "AKHAURA",
  },
  {
    id: 6,
    EIIN: "103154",
    schoolName: "DEBGRAM GOVERNMENT PILOT HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "AKHAURA",
  },
  {
    id: 7,
    EIIN: "103155",
    schoolName: "MOGORA HIGH SCHOOL, GONGASAGAR",
    zilla: "BRAHMANBARIA",
    upazila: "AKHAURA",
  },
  {
    id: 8,
    EIIN: "103156",
    schoolName: "TULAI SHIMUL HIGH SCHOOL, COLONEL BAZAR",
    zilla: "BRAHMANBARIA",
    upazila: "AKHAURA",
  },
  {
    id: 9,
    EIIN: "103157",
    schoolName: "HIRAPUR SHAHID NOWAB MEMORIAL HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "AKHAURA",
  },
  {
    id: 10,
    EIIN: "103158",
    schoolName:
      "RANIKHAR S. A. HANNAN BOHUMUKHI AND KARIGARI HIGH SCHOOL, GHOLKHAR",
    zilla: "BRAHMANBARIA",
    upazila: "AKHAURA",
  },
  {
    id: 11,
    EIIN: "103159",
    schoolName: "KARMAMOTH HIGH SCHOOL, KARMA MOTH",
    zilla: "BRAHMANBARIA",
    upazila: "AKHAURA",
  },
  {
    id: 12,
    EIIN: "103161",
    schoolName: "CHHOYGHARIA AL-HAJ SHAH ALAM HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "AKHAURA",
  },
  {
    id: 13,
    EIIN: "103162",
    schoolName: "AMODABAD ALHAJ SHAH ALAM HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "AKHAURA",
  },
  {
    id: 14,
    EIIN: "103170",
    schoolName: "CHHATURA CHANDPUR SCHOOL AND COLLEGE",
    zilla: "BRAHMANBARIA",
    upazila: "AKHAURA",
  },
  {
    id: 15,
    EIIN: "103171",
    schoolName: "DARIKANDI BADDA ASMATUNNESA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 16,
    EIIN: "103172",
    schoolName: "KHALLA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 17,
    EIIN: "103173",
    schoolName: "BANCHARAMPUR GOVT. S. M. PILOT MODEL HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 18,
    EIIN: "103174",
    schoolName: "BANCHHARAMPUR GIRLS' PILOT HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 19,
    EIIN: "103175",
    schoolName: "UJANCHAR K. N. HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 20,
    EIIN: "103176",
    schoolName: "RUPASDI BRINDABON HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 21,
    EIIN: "103177",
    schoolName: "MORICHA KANDI D. T. ACADEMY, MORICHA KANDI",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 22,
    EIIN: "103178",
    schoolName: "DARIA DAULAT ABDUL GANI HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 23,
    EIIN: "103179",
    schoolName: "DHARIAR CHAR HAZI OMAR ALI HIGH SCHOOL, DHARIAR CHAR BAZAR",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 24,
    EIIN: "103180",
    schoolName: "TEJKHALI UNION HIGH SCHOOL, TEJKHALI",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 25,
    EIIN: "103181",
    schoolName: "H. K. ASMATUNNESA HIGH SCHOOL, PAHARIAKANDI",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 26,
    EIIN: "103182",
    schoolName: "SHAH RAHAT ALI HIGH SCHOOL, CHHAYFULLAH KANDI",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 27,
    EIIN: "103183",
    schoolName: "FARDABAD HIGH SCHOOL, FARDABAD",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 28,
    EIIN: "103184",
    schoolName: "RUPASDI JAMIDA MUNSOOR ALI HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 29,
    EIIN: "103185",
    schoolName: "BAHER CHAR ADARSHA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 30,
    EIIN: "103187",
    schoolName: "BHURBHURIA ADARSHA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 31,
    EIIN: "103188",
    schoolName: "ASHRAFBAD HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 32,
    EIIN: "103190",
    schoolName: "AYUBPUR CAPTAIN A. B. TAJUL ISLAM HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BANCHHARAMPUR",
  },
  {
    id: 33,
    EIIN: "103205",
    schoolName: "BODHAL HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 34,
    EIIN: "103206",
    schoolName: "BULLA ADARSHA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 35,
    EIIN: "103207",
    schoolName: "ULCHAPARA MALEKA SHAEB ALI HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 36,
    EIIN: "103208",
    schoolName: "SHALGAON KALISHIMA SCHOOL AND COLLEGE",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 37,
    EIIN: "103209",
    schoolName: "ISLAMPUR ALHAJ KAZI RAFIQUL ISLAM HIGH SCHOOL AND COLLEGE",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 38,
    EIIN: "103210",
    schoolName: "ANNADA GOVT. HIGH SCHOOL, BRAHMANBARIA",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 39,
    EIIN: "103211",
    schoolName: "BRAHMANBARIA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 40,
    EIIN: "103212",
    schoolName: "BRAHMANBARIA IDEAL HIGH ACADEMY",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 41,
    EIIN: "103213",
    schoolName: "GOVERNMENT HAZI ABDUL JALIL HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "ASHUGANJ",
  },
  {
    id: 42,
    EIIN: "103214",
    schoolName: "ROWSHAN ARA JALIL GIRLS' HIGH SCHOOL, ASHUGONJ",
    zilla: "BRAHMANBARIA",
    upazila: "ASHUGANJ",
  },
  {
    id: 43,
    EIIN: "103215",
    schoolName: "RAMKANAI HIGH SCHOOL, BRAHMANBARIA",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 44,
    EIIN: "103216",
    schoolName: "SABERA SOBHAN GOVT. GIRLS' HIGH SCHOOL, BRAHMANBARIA",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 45,
    EIIN: "103217",
    schoolName: "ANANDAMOYI GIRLS' HIGH SCHOOL, BRAHMANBARIA",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 46,
    EIIN: "103218",
    schoolName: "NIAZ MOHAMMAD HIGH SCHOOL, BRAHMANBARIA",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 47,
    EIIN: "103220",
    schoolName: "BADHUGHAR MAHBUBUL HUDA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 48,
    EIIN: "103221",
    schoolName: "BAKAIL HIGH SCHOOL, SUHILPUR",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 49,
    EIIN: "103222",
    schoolName: "SATBARGA HIGH SCHOOL, B.BARIA",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 50,
    EIIN: "103223",
    schoolName: "BARAIL HOSAINIA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "NABINAGAR",
  },
  {
    id: 51,
    EIIN: "103224",
    schoolName: "DAUDPUR GOVERNMENT HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 52,
    EIIN: "103225",
    schoolName: "GOVT. MODEL GIRLS' HIGH SCHOOL, BRAHMANBARIA",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 53,
    EIIN: "103226",
    schoolName: "CHANDPUR TAMIZ UDDIN HIGH SCHOOL, BRAHMANBARIA",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 54,
    EIIN: "103227",
    schoolName: "MIRASHANI POLYTECHNIC ACADEMY, MIRASHANI",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 55,
    EIIN: "103228",
    schoolName: "SULTAN PUR HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 56,
    EIIN: "103229",
    schoolName: "AUSHTAGRAM HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 57,
    EIIN: "103230",
    schoolName: "BASUDEB HIGH SCHOOL, BASUDEB",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 58,
    EIIN: "103231",
    schoolName: "GHATIARA HIGH SCHOOL, GHATIARA",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 59,
    EIIN: "103232",
    schoolName: "NIDARABAD UNION HIGH SCHOOL, HARESHPUR",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 60,
    EIIN: "103233",
    schoolName: "HABLA ADARSHA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 61,
    EIIN: "103234",
    schoolName: "TARUA GIRLS' HIGH SCHOOL, TARUA",
    zilla: "BRAHMANBARIA",
    upazila: "ASHUGANJ",
  },
  {
    id: 62,
    EIIN: "103235",
    schoolName: "BISHNU PUR HIGH SCHOOL, BISHNU PUR",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 63,
    EIIN: "103236",
    schoolName: "ZILLUR RAHAMAN HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 64,
    EIIN: "103237",
    schoolName: "SHAH FARASAT ALI HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "ASHUGANJ",
  },
  {
    id: 65,
    EIIN: "103238",
    schoolName: "MUKUNDA PUR HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 66,
    EIIN: "103239",
    schoolName: "ASHUGANJ TAP BIDYUT KENDRA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "ASHUGANJ",
  },
  {
    id: 67,
    EIIN: "103241",
    schoolName: "ARAISIDHA K. B. HIGH SCHOOL, ARAISIDHA",
    zilla: "BRAHMANBARIA",
    upazila: "ASHUGANJ",
  },
  {
    id: 68,
    EIIN: "103242",
    schoolName: "RAMRAIL D. N. DATTA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 69,
    EIIN: "103243",
    schoolName: "CHATTURPUR HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 70,
    EIIN: "103244",
    schoolName: "BIJESHWAR A. MONEM HIGH SCHOOL, ULCHAPARA",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 71,
    EIIN: "103245",
    schoolName: "ISLAMPUR HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 72,
    EIIN: "103246",
    schoolName: "MAINDA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 73,
    EIIN: "103247",
    schoolName: "PATTAN HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 74,
    EIIN: "103248",
    schoolName: "CHANPUR ADARSHA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 75,
    EIIN: "103249",
    schoolName: "PAHARPUR UNION HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 76,
    EIIN: "103250",
    schoolName: "MOHESHPUR HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 77,
    EIIN: "103251",
    schoolName: "ARIOL HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 78,
    EIIN: "103252",
    schoolName: "SATIRPARA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 79,
    EIIN: "103253",
    schoolName: "SHOHATA GIRL'S HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 80,
    EIIN: "103254",
    schoolName: "SADAKPUR UNION HIGH SCHOOL AND COLLEGE",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 81,
    EIIN: "103255",
    schoolName: "CHAURA KABI SANAUL HAQ HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 82,
    EIIN: "103256",
    schoolName: "KOKIL TEXTILE MILL HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 83,
    EIIN: "103257",
    schoolName: "PAYAG NARSHINGSHAR A. BARI HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 84,
    EIIN: "103258",
    schoolName: "EKTARPUR ADARSHA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 85,
    EIIN: "103259",
    schoolName: "UJANISHAR JOYNAL ABEDIN KHAN HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 86,
    EIIN: "103260",
    schoolName: "PANCHGAON ADARSHA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 87,
    EIIN: "103261",
    schoolName: "KALACHARA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 88,
    EIIN: "103262",
    schoolName: "CHILOKUT HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 89,
    EIIN: "103263",
    schoolName: "LAXMIMURA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 90,
    EIIN: "103264",
    schoolName: "CHAPUIR AZIZUL HAQUE HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 91,
    EIIN: "103265",
    schoolName: "AHARANDA MOHIUDDIN NAGAR HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 92,
    EIIN: "103266",
    schoolName: "POLICE LINE HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 93,
    EIIN: "103267",
    schoolName: "KHATINGA GIRLS HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 94,
    EIIN: "103268",
    schoolName: "GOWTAM PARA GHATURA BANGABANDHU HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 95,
    EIIN: "103269",
    schoolName: "MAJLISHPUR HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 96,
    EIIN: "103270",
    schoolName: "BANGO BANDHU SHIEKH MOJIBUR RAHMAN HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 97,
    EIIN: "103298",
    schoolName: "CHINAIR ANZUMAN ARA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 98,
    EIIN: "103299",
    schoolName: "BANGLADESH GAS FIELDS SCHOOL & COLLEGE",
    zilla: "BRAHMANBARIA",
    upazila: "BRAHMANBARIA SADAR",
  },
  {
    id: 99,
    EIIN: "103302",
    schoolName: "CHAMPAK NAGAR HIGH SCHOOL, NURPUR",
    zilla: "BRAHMANBARIA",
    upazila: "BIJOYNAGAR",
  },
  {
    id: 100,
    EIIN: "103303",
    schoolName: "TALSHAHAR A. A. I. HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "ASHUGANJ",
  },
  {
    id: 101,
    EIIN: "103304",
    schoolName: "KAMAURA SHAHID SREETI HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "ASHUGANJ",
  },
  {
    id: 102,
    EIIN: "103305",
    schoolName: "HAZI ABDUL QUDDUS SCHOOL & COLLEGE",
    zilla: "BRAHMANBARIA",
    upazila: "ASHUGANJ",
  },
  {
    id: 103,
    EIIN: "103306",
    schoolName: "TALSHAR BUDHAI SAHA JR HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "ASHUGANJ",
  },
  {
    id: 104,
    EIIN: "103307",
    schoolName: "LALPUR S. K. DAS CHOWDHURY HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "ASHUGANJ",
  },
  {
    id: 105,
    EIIN: "103308",
    schoolName: "DURGAPUR HIGH SCHOOL, BAHADURPUR",
    zilla: "BRAHMANBARIA",
    upazila: "ASHUGANJ",
  },
  {
    id: 106,
    EIIN: "103309",
    schoolName: "SOHAGPUR ACHIYA SAFIUDDIN ADARSHA MADHYAMIK SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "ASHUGANJ",
  },
  {
    id: 107,
    EIIN: "103312",
    schoolName: "ASHUGANJ SAR KARKHANA COLLEGE",
    zilla: "BRAHMANBARIA",
    upazila: "ASHUGANJ",
  },
  {
    id: 108,
    EIIN: "103313",
    schoolName: "RABEYA MANNAN BHUIYAN GIRLS' HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "KASBA",
  },
  {
    id: 109,
    EIIN: "103315",
    schoolName: "TALTALA ADARSHA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "KASBA",
  },
  {
    id: 110,
    EIIN: "103316",
    schoolName: "MANDERPUR HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "KASBA",
  },
  {
    id: 111,
    EIIN: "103317",
    schoolName: "MULAGRAM HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "KASBA",
  },
  {
    id: 112,
    EIIN: "103318",
    schoolName: "B.B.DR. HABIBUR RAHMAN HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "KASBA",
  },
  {
    id: 113,
    EIIN: "103319",
    schoolName: "CHARGACHH N. I. BHUIYA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "KASBA",
  },
  {
    id: 114,
    EIIN: "103320",
    schoolName: "MOINPUR HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "KASBA",
  },
  {
    id: 115,
    EIIN: "103321",
    schoolName: "KAYEMPUR ADARSHA HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "KASBA",
  },
  {
    id: 116,
    EIIN: "103322",
    schoolName: "SONAR BANGLA ADVOCATE SERAJUL HUQ HIGH SCHOOL",
    zilla: "BRAHMANBARIA",
    upazila: "KASBA",
  },
];

module.exports = list;
